### ISSUE TITLE
Formatin of the Prices is wrong

### ISSUE THREAD

**Issue by Schmiddyyy** [olech2412/EGR#18]
### The format in the prices are wrong e.g. 4.5€ instead of 4,50€

**Comment by olech2412** [comment]
Danke das Sie das Problem gemeldet haben. Leider haben Sie das Ticket für das falsche Repository aufgemacht. Bitte eröffnen Sie ein neues Ticket beim EssensGetter2.0

**Comment by olech2412** [comment]
Ich habe das Ticket für Sie verschoben und werden es damit in diesem Repository schließen. Für weitere Informationen: https://github.com/olech2412/EssensGetter-2.0/issues/12
